name: Build .NET MAUI SmartShopper

on:
  push:
    branches: [ "main", "developer" ]
  pull_request:
    branches: [ "main", "developer" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install MAUI workloads
      run: dotnet workload install maui-android maui-ios maui-maccatalyst --ignore-failed-sources

    - name: Restore dependencies
      run: dotnet restore ./SmartShopperApp/SmartShopperApp.csproj

    - name: Build SmartShopper (MacCatalyst)
      run: dotnet build ./SmartShopperApp/SmartShopperApp.csproj -c Release -f net8.0-maccatalyst

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SmartShopper-maccatalyst
        path: SmartShopperApp/bin/Release/net8.0-maccatalyst/**/*.app
